name: E2E tests on Windows

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  e2e_tests:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [windows-2019, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: install scoop (Windows)
        if: runner.os == 'Windows'
        uses: MinoruSekine/setup-scoop@v3
  
      - name: install vfox (Windows)      
        if: runner.os == 'Windows'
        run: |
          scoop install vfox          

      - name: add vfox-erlang plugin (Windows) 
        if: runner.os == 'Windows'
        run: |
          vfox add --source https://github.com/version-fox/vfox-erlang/archive/$env:GITHUB_REF.zip erlang

      - name: install Erlang/OTP by vfox-erlang plugin (Windows)
        if: runner.os == 'Windows'
        run: |
          vfox install erlang@25.3.2.12
          vfox use erlang@25.3.2.12
          if (-not (Test-Path -Path $PROFILE)) { New-Item -Type File -Path $PROFILE -Force }; Add-Content -Path $PROFILE -Value 'Invoke-Expression "$(vfox activate pwsh)"'
      - name: test installation
        if: runner.os == 'Windows'
        run: |
          Invoke-Expression "$(vfox activate pwsh)"
          echo "===============PATH==============="
          echo $env:PATH
          echo "===============PATH==============="
          & erl.exe -eval 'erlang:display({otp_release, erlang:system_info(otp_release)}), halt().' -noshell
          & erl.exe -eval 'erlang:display(shell_docs:get_doc(lists)), halt().' -noshell
