name: E2E tests on Darwin MacOS (mise)

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  e2e_tests:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: install Erlang/OTP by mise with vfox-erlang plugin (Darwin)
        if: runner.os == 'MacOS'
        run: |
          brew install --force autoconf libxslt fop wxwidgets openssl
          export MAKEFLAGS=-j4
          mise use -g vfox:version-fox/vfox-erlang@26.2.3
          mise exec -- erl -version
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          cd assets
          mise exec -- erlc hello.erl
          mise exec -- erl -noshell -s hello hello_world -s init stop
          mise exec -- erl -eval 'erlang:display(shell_docs:get_doc(lists)), halt().' -noshell