name: E2E tests on Linux (Prebuilt release)

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: '0 0 * * *'

jobs:
  e2e_tests:
    strategy:
      matrix:
        # ref: https://github.com/actions/runner-images
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: install vfox (Linux)
        run: |
          echo "deb [trusted=yes] https://apt.fury.io/versionfox/ /" | sudo tee /etc/apt/sources.list.d/versionfox.list
          sudo apt-get update
          sudo apt-get install vfox

      - name: add vfox-erlang plugin (Unix-like) 
        run: |
          vfox add --source https://github.com/version-fox/vfox-erlang/archive/${GITHUB_REF}.zip erlang
      
      - name: prepare Erlang/OTP deps (Linux)
        run: |
          sudo DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential autoconf m4 libncurses5-dev libwxgtk3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libgl1-mesa-dev libglu1-mesa-dev libpng-dev libssh-dev unixodbc-dev xsltproc fop libxml2-utils libncurses-dev openjdk-11-jdk
      
      - name: install Erlang/OTP by vfox-erlang plugin (Linux)
        shell: bash
        run: |
          export MAKEFLAGS=-j4
          export USE_PREBUILT_OTP="ubuntu-22.04"
          vfox install erlang@maint-27
          # Hook Shell
          echo 'eval "$(vfox activate bash)"' >> "$HOME/.bash_profile"

      - name: test installation
        shell: bash --norc -l -e -o pipefail {0} # use login shell to load .bashrc:
        run: |
          vfox use -s erlang@maint-27
          source "$HOME/.bash_profile"
          echo "===============PATH==============="
          echo $PATH
          echo "===============PATH==============="
          cd assets
          erlc hello.erl
          erl -noshell -s hello hello_world -s init stop
